Extract thread logic from Mopy library
hulthe/DAT255 pull request #15
Opened 2017-09-26 09:21 UTC by Levis92

2017-09-26 09:35 UTC, fantomsol submitted a review, later dismissed

2017-09-26 09:35 UTC, LumoIT commented on mopy/src/main/java/it/chalmers/digit/Mopy.java
`instance` is not initialized, thus program does not run.

2017-09-26 09:35 UTC, LumoIT commented on mopy/src/main/java/it/chalmers/digit/Mopy.java
>  public final class Mopy implements MopedController {
Mopy should have a private constructor.

2017-09-26 15:03 UTC, Levis92 commented on mopy/src/main/java/it/chalmers/digit/Mopy.java
>  public final class Mopy implements MopedController {
It has now 😉

2017-09-28 06:28 UTC, hulthe requested changes

2017-09-28 06:28 UTC, hulthe commented on mopy/src/main/java/it/chalmers/digit/Mopy.java
>  					instance = new Mopy();
`instance` should be instantiated on program startup

2017-09-28 06:48 UTC, hulthe approved these changes

2017-09-28 06:49 UTC, merged